### ISSUE TITLE
Can it be used in react native?

### ISSUE THREAD

**Issue by PonorogoCreativeIT** [CharlesStover/reactn#12]
Can it be used in react native?

**Comment by CharlesStover** [comment]
I am almost positive that it can. The only reason I'm not completely positive is because I haven't tested it personally. It piggybacks off the React installation, and react-native still uses the react package, so I don't see why it wouldn't. If you want to try it, I would definitely be interested in fixing any errors you run into; but I do not believe you would run into any errors.

Please keep me informed. I certainly want this to be compatible with React Native. :)

**Comment by CharlesStover** [comment]
Closing this, because there is no reason React Native wouldn't be supported. If anyone has a problem integrating with RN, feel free to open a new issue.
