### ISSUE TITLE
Diff between useGlobal() and useGlobal('someProperty')

### ISSUE THREAD

**Issue by m4ttheweric** [CharlesStover/reactn#121]
I have some state stored using createProvider(). The state has quite a few properties, so I am making use of it by going with 

`const [state, setState] = MyProvider.useGlobal()`

I have a component that needs a boolean to show/hide itself (it's a Material-UI dialog). I pass it the state.show property and when I update that property in another module using a set, it doesn't seem to open the dialog except when I do some other action to re-render the parent components. However, if instead I bring in the 'show' property like so:

`const [show, setShow] = MyProvider.useGlobal('show')`

Then everything works swimmingly. 

Is there a difference between how a component listens to the state based on whether you use the entire state or just a property?

**Comment by CharlesStover** [comment]
As far as subscriptions are concerned, `global.show` and `useGlobal('show')` should both cause the component to re-render when that value changes.

The only exception to this would be `MyProvider.getGlobal()`, as the `getGlobal` helper function is explicitly designed to not subscription so that it can be used outside of components (e.g. in helper libraries).

I might need to see a minimal reproduction if possible, as this would be a bug as described. It may be that some other issue is causing it to appear like this is occurring. [Here is the unit test](https://github.com/CharlesStover/reactn/blob/master/tests/use-global/undefined.test.ts#L74) that verifies that accessing a property on `useGlobal()`'s returned state should trigger a re-render when that property changes. If there is an edge case where this doesn't happen, I would like it to be identified, fixed, and tested as well. :)

**Comment by m4ttheweric** [comment]
Thanks for the quick reply @CharlesStover. I will try to drum up an example of this in the near future if I can or report back if I am able to isolate what is happening.

**Comment by CharlesStover** [comment]
Was this able to be reproduced?
