### ISSUE TITLE
Implement global state life cycle methods.

### ISSUE THREAD

**Issue by slevy85** [CharlesStover/reactn#23]
Hi,

I have experiment this behavior :
- I use this.global.x in `componentDidUpdate` in component A
- When component B updates global.x, component A doesn't rerender
- I make something else to make component A render
- Then when component B updates global.x it does make component A render

I suppose that before the first call of `componentDidUpdate`, we don't know that component A is using `global.x`, so it is not rerendered until something make it call `componenetDidUpdate`, at this time we see that component A uses `global.x`.

I am not sure my issue is clear, is it the expected behavior or do you think it can be changed ?

Thank you

**Comment by CharlesStover** [comment]
I think I understand. There is no way for the global state to know
component A uses global.x until it actually tries to access global.x. This
behavior cannot be bypassed by JavaScript -- there's no way to know that a
property _may_ be accessed. Either it was accessed it or wasn't. On the
same hand, this behavior is desirable:
if (global.y) { console.log(global.x); }
If global.y is false, this component shouldn't re-render when x changes,
because this component does not even use x.

You could use global.x in your componentDidMount to force the subscription
on mount.
You could use the withGlobal HOC to pass x as a prop instead of as the
global member variable, which will subscribe to x even pre-update.

If you have other suggestions for resolving this situation, I am open to
hearing them. As my current understanding of the situation, it's not
possible for the global state to know that component A wants to subscribe
to it.

**Comment by slevy85** [comment]
Thank you for your answer,

Yes I think that I have to use the variable somewhere to suscribe to it, I didn't think of the HOC solution, it may be a better solution if it is explicit.

Maybe a solution : 
```javascript
// empty function to notify reactn we use some variables
suscribe(){}

componentDidMount(){
   suscribe(this.global.x)
}
```
Thank you

**Comment by slevy85** [comment]
I have another question about `componentDidUpdate`.
Is it usable with reactn ?
I mean, are we notified of the previous state of `this.global` ?

**Comment by CharlesStover** [comment]
**RE: subscribe method**
You can just do this:
```JavaScript
componentDidUpdate() {
  this.global.x;
}
```

Even though global.x isn't _used_, it is accessed, causing a subscription to updates with the component.

**RE: previous global state**
I've actually not thought of that, but the previous global state is not accessible. This may take some brainstorming before implementing, because there are multiple ways to tackle it:
* `componentDidUpdate(prevProps, prevState, prevGlobal)`
* `this.prevGlobal`
* `componentDidUpdateGlobal(prevGlobal)`

I like the first choice, but I think it is only supported by the decorator `@reactn` syntax and not by the `import React from 'reactn';` syntax. But again, it will take brainstorming before settling on anything.

In the mean time, the `withGlobal` HOC will convert global to props, which will be included in `prevProps`.
```JavaScript
export default withGlobal(
  // Convert global.x into props.x
  global => ({
    x: global.x
  })
)(ComponentA);
```

**Comment by slevy85** [comment]
I also would prefer the first one because we can they mix operation between `prevProps`, `prevState` and `prevGlobal`.
But there are use case when react passes a third parameter to this method when used with `getSnapshotBeforeUpdate(prevProps, prevState)`, then we have `componentDidUpdate(prevProps, prevState, snapshot)`. see here https://reactjs.org/docs/react-component.html#shouldcomponentupdate.

I don't like the second one, `this.prevGlobal`, because I don't we should use `prevGlobal` everywhere but just in a function.

The third one is also good `componentDidUpdateGlobal(prevGlobal)`.
And it makes me think that we should have the same for every function of react, like `shouldComponentUpdate(nextProps, nextState)`, `shouldComponentUpdateGlobal(nextGlobal)`.

**Comment by CharlesStover** [comment]
I'll reply more thoroughly to your feedback later today or tomorrow. I wanted to note globalDidUpdate as an option before I forget.

**Comment by CharlesStover** [comment]
>I also would prefer the first one because we can they mix operation between prevProps, prevState and prevGlobal.

I agree, but I think it is a limitation. ReactN does not modify React or React Fiber. The dispatch of component lifecycle methods is handled by React Fiber. Customizing them can't be done without modifying React Fiber. A major advantage of ReactN is that it does not mutate React or its internals, allowing for a simultaneous install of the two packages and guaranteed non-interference.

I may go with the last choice and implement lifecycle methods for global. I also like the idea of `shouldComponentUpdateGlobal` (or `shouldGlobalUpdate`), not sure which naming convention to adopt yet.

**Comment by CharlesStover** [comment]
They are both based on the React naming convention. One is the React method + Global, while the other is the React method replacing Component with Global. But the React method + Global is probably more clear as to what it is doing, so I will go with that. e.g. You aren't determining if the global state should update.

**Comment by EskelCz** [comment]
I could use this as well, any ETA? :) thanks

**Comment by kevindavis** [comment]
Has something that provides this functionality been added to a recent version? I'm finding myself wanting to do something like this..

**Comment by CharlesStover** [comment]
It is not. Support of class components is likely not the direction in which new ReactN features will head.

**Comment by kevindavis** [comment]
Could you elaborate a bit more? Apologies I'm new to this. How would one achieve this with functional components ?

**Comment by CharlesStover** [comment]
```
import { useGlobal } from 'reactn';

function MyApp() {
  const [x] = useGlobal('x');
}
```

If you use the global state hooks from the ReactN package, as documented in the README on this repository, you should not encounter the problem outlined in this issue, which is unique to class components.
