### ISSUE TITLE
Why make it a drop-in replacement?

### ISSUE THREAD

**Issue by dandrei** [CharlesStover/reactn#26]
Not an issue, but a question.

I understand that reactn is a drop-in replacement for React that adds the ability to have global state.

What is the reason to do things this way, as opposed to having it shipped as a module to be used alongside standard React?

Isn't it hard to have to keep the two in sync?

Thanks!

**Comment by kajmagnus** [comment]
I also have those questions :- )

Can I ask another similar question? What are your thoughts about if having access to useGlobal everywhere, and maybe-a-risk that people start using globals too often? I mean, generally, in software, one tries to avoid globals? Maybe, though, this could be a problem with things like Redux too?

**Comment by CharlesStover** [comment]
Thanks for reaching out and participating in the project's community!

>What is the reason to do things this way, as opposed to having it shipped as a module to be used alongside standard React?

Minimal boilerplate and non-mutating the React package itself.

Example alternatives that do neither:

Redux is a module to be used alongside React. As a result, you have to add a lot of Redux boilerplate to both create the Redux objects and integrate them with React components. Since ReactN occurs behind the scenes, you neither need to create the ReactN objects nor integrate them with your React components.

WhyDidYouUpdate is a popular package that mutates the React object itself. This is reasonable, because it only does so _in development environments_, leaving the React package untouched in production builds. As a result, the boilerplate is practically non-existent. Unlike WhyDidYouUpdate, ReactN must be shipped in production builds. Mutating the React package was a design choice deemed inappropriate for ReactN.

>Isn't it hard to have to keep the two in sync?

Not at all! They don't have to be synced! ReactN does not include React, React-logic, or the underlying React powerhouse known as React Fiber. ReactN imports whatever version of React you already have installed, copies it verbatim (leaving the original untouched), and merely _adds_ functionality. As a result, maintaining ReactN only requires maintaining the ReactN logic. If a new React package comes out, ReactN is already copying it. If a user downgrades their React package, ReactN will use that downgraded version instead.

The ReactN package looks like this, in pseudo-code:

```
import React from 'react';

export default {
  ...React,
  newFunctionality: () => {},
  helperFunction: () => {},
  globalStuff: () => {}
};
```

Maintaining ReactN involves maintaining those additional properties. React changes get implemented auto-magically.

>Can I ask another "meta question"? What are your thoughts about if having access to useGlobal everywhere, and maybe-a-risk that people start using globals too often?

I'm not sure using globals too often is a real concern. People should probably be using them more than they are currently. That was the goal of this package. There are real times that developers should be using global state _but aren't_ because alternatives are too difficult to implement. They would rather hard-code a local state that prop-drills and passes around to sibling's great-grandchildren than write and maintain boilerplate. It's a valid complaint, and I wanted to remove that constraint from developers (myself included).

>I mean, generally, in software, one tries to avoid globals? Maybe, though, this could be a problem with things like Redux too?

You should try to avoid globals in software because they often conflict with one another. If your React app is responsible for half of your webpage with an Angular app being responsible for the other half, you don't want both apps using the `window` namespace to store variables -- eventually, they will try to use the same property of `window` and overwrite each others' data. That's the fear of globals.

ReactN's global is tied to your React application. It does not pollute a global namespace for non-React projects that may share the global scope. It is "global" in the sense that it is accessible to your entire React project, but it is not "global" in the sense of the global scope `window` (in browser) or `global` (in NodeJS).

**Comment by CharlesStover** [comment]
Functions pre-16.7 do not have state, so they cannot access stateful features like Hooks allow. While it would be possible to access the global state in a functional component, since that functional component is not stateful, it would not be able to re-render when the global state changes. There is no "instance" of the component to tell to re-render now that the global value it is displaying has changed.

You can `import { withGlobal } from 'reactn'` for a HOC to pass the global state as props to your functional component. That HOC will re-render with the global state change, which will cause your functional component to re-render as well.

**Comment by kajmagnus** [comment]
@CharlesStover  Thanks for the replies and explanations

> There are real times that developers should be using global state but aren't because alternatives are too difficult to implement. They would rather hard-code a local state that prop-drills and passes around to sibling's great-grandchildren than write and maintain boilerplate

I recognize that to some degree. I have a sort-of-global thing with "everything" as various fields, which I prop-drill down down down. Works ok, since it's just one prop. Anyway, this sort of means I have a global object + field already.

Will be interesting to see if React 16.7 will include hooks ... then this Globals approach, I think I like it :-)
