### ISSUE TITLE
Why React doesn't implement the same - a global state?

### ISSUE THREAD

**Issue by manyopensource** [CharlesStover/reactn#32]

**Comment by CharlesStover** [comment]
The Facebook team, which makes React, are fans of Flux architecture, where views do not work directly with the state. Instead, they support the dispatching of actions which in turn mutate the state which in turns trickles down to re-render the views. This concept is powerful for large organizations with extensive code bases. It helps onboarding new developers and prevent side-effects and unforeseen bugs. In exchange, you have more boilerplate and a steeper learning curve. This is why they made Redux.

Redux isn't built into React, because the concept behind Flux is that state and view are totally separate. You can use Redux with non-React apps, and you can use React with non-Redux global state (such as ReactN). Keeping global state out of React allows for a more streamlined package that doesn't include features you aren't looking for. Apps without global state are significantly smaller due to the global state logic not being bundled in to their React code, and apps that don't want to harness Flux architecture are similarly benefited by not having Flux built into it.

I guess in short, how to manage global state is a very opinionated topic that is still evolving, and the Facebook team didn't want to make that decision for you. 😄

**Comment by QuantumInformation** [comment]
Would love React to integrate this global state. The amount of redux boilerplate is not fun, and Vue takes more and more dev uptake.
