### ISSUE TITLE
Support non-object global states.

### ISSUE THREAD

**Issue by mmkal** [CharlesStover/reactn#46]
Something that would help with typescript/flow typings, as well as make it easier to use the package correctly - instead of hinting that global state should be initialised before ever calling `useGlobal`, you could be sure that `setGlobal` had been called, if that were the recommended/only way to get the `useGlobal` reference:

```js
// state.js
import { setGlobal } from 'reactn';
export const useGlobal = setGlobal({
  cards: [],
  disabled: false,
  initial: 'values',
  x: 1
});
```
```js
// index.js
import ReactDOM from 'react-dom';
import App from './App';

// no need to call `useGlobal` here:
// it'll be called when the module is `require(...)`d for the first time.
ReactDOM.render(
  <App />,
  document.getElementById('root')
);
```
```js
// SomeComponent.js
import { useGlobal } from './state'
export const SomeComponent = () => {
  const [state, setGlobal] = useGlobal()
  return <div>{state.cards.join(', ')}</div>
}
```

In `index.d.ts`, `setGlobal` could be typed with a generic to so `useGlobal` could also have useful types (right now, `{ [property: string]: any }` which allows any property access with no restrictions and no hints):

```typescript
export function setGlobal<State>(initialState: State): UseGlobal<State>
interface UseGlobal<State> {
  (): UseGlobalResult<State>
  <Key extends keyof State>(key: Key): UseGlobalResult<State[Key]>
}
type UseGlobalResult<T> = [T, (newState: T) => void]
```

You then get meaningful autocomplete out-of-the-box. This would work even in javascript in most IDEs, because the type passed in to `setGlobal` can be inferred. Example:

![image](https://user-images.githubusercontent.com/15040698/53812724-11b8a280-3f2a-11e9-8760-7b1f87c84b7d.png)

Here the compiler finds the bug - that we're trying to pass in a number to `cards`, which is an array of strings.

One other possible benefit (although possibly not initially; it would depend on the implementation) is that by being more functional - returning a function rather than relying on side-effects - you could conceivably have multiple state objects that can span components.

What do you think? If you'd be open to the change I could help with a PR.

**Comment by mmkal** [comment]
Linking some issues/comments that might be fixed/improved by this: https://github.com/CharlesStover/reactn/issues/31 https://github.com/CharlesStover/reactn/issues/27 https://github.com/CharlesStover/reactn/issues/26#issuecomment-443041615

**Comment by CharlesStover** [comment]
I do think it is interesting to be able to automatically infer types like this, but it isn't fool-proof. If I call setGlobal in two different components, they won't share the inferred type, even though they will share the state.

You can manually infer type of `useGlobal` with a generic.

`const [ cards, setCards ] = useGlobal<string[]>('cards');`

I don't like that that has to be manually done, but I've not been able to resolve it.

If `setGlobal` were to return anything, I think it would be a Promise for asynchronous state management.

```JavaScript
setGlobal(
  fetch('/api/data')
)
  .then(newGlobalState => { /* ... */ });
```

I think this is particularly important because React's default behavior is to set (local) state asynchronously.

**Comment by mmkal** [comment]
> I do think it is interesting to be able to automatically infer types like this, but it isn't fool-proof. If I call setGlobal in two different components, they won't share the inferred type, even though they will share the state.

That's true, even if ideally it wouldn't be. It's also true right now already. If you call `setGlobal` in two places it'll result in confusing behaviour based on import order because they'll fight with each other over the global state. Under this proposal the types would then also be confusing, reflecting that runtime ambiguity. If multiple state objects can't work, then this could just become a "don't do that" situation. i.e. some documentation recommending users to call `setGlobal` only once. Anyone who wants to stray from the recommendation can cast to `any` in  typescript, and do whatever weird stuff they want from there.

> If setGlobal were to return anything, I think it would be a Promise for asynchronous state management.

That would definitely make things more complex in terms of the usage and the types. But given `setGlobal` returns a hook function, might it be ok to return the _function_ synchronously, even if the _data_ won't arrive until later? The data should always be fetched with `useGlobal`, so will yield a value and cause a render whenever it's ready.

> I often recommend [calling `setGlobal` before `useGlobal`], but I don't think of it as a requirement. useGlobal('cards') returning undefined makes sense to me, the same way anyObject.cards returning undefined makes sense.

Maybe the existing `useGlobal` import could be typed as `UseGlobal<Record<string, undefined>>`, so if people really want to start from no state at all, they can, and `useGlobal('cards')` would be of type `undefined` as expected. My personal opinion on this is to just to recommend  `setGlobal({})` instead if you want an empty initial state, so that there aren't many ways of doing the same thing. It'd make the library simpler. It's easier to reason about too re things like the difference between an empty state (`state = {}`) and an undefined state (`state = undefined`).

> [multiple state objects] works for hooks, but it doesn't help class Components

Fair enough. I found this library because I wanted a cleaner alternative to redux that used react hooks, so my initial assumption was that this library would only support hooks. I'm definitely biased because of that, but I'd love it if `reactn` focused only on hooks, and dropped `Components` completely over supporting the two of them with a more limited feature set.

**Comment by CharlesStover** [comment]
>It's easier to reason about too, like the difference between an empty state (state = {}) and an undefined state (state = undefined).

For reference, the state object is never `undefined`. It instantiates to an empty object. If you never call `setGlobal`, the state isn't `undefined`, it is just `{}` with no properties.

>Anyone who wants to stray from the recommendation can cast to any in typescript, and do whatever weird stuff they want from there.

I want to avoid `any` at all costs, not use it as an escape to design decisions. It's one thing to use it in ReactN itself, which I don't want if I can help it, but worse to force users to use it. There are lint rules that prevent the use of `any` altogether that would, out of the box, make ReactN incompatible with their project.

>But given setGlobal returns a hook function, might it be ok to return the function synchronously, even if the data won't arrive until later?

I'm not sure about the feasibility of returning a _function_ that is also an instance of a _Promise_. I have a feeling that Promise internals will rely on `this` to point to a Promise and not a function, and it would be confusing to users to see the return value used both as a function and a Promise.

>It'd make the library simpler.

I'm just not sure I see having to import the return value of `setGlobal` in all your files as easier than not having to import anything. The point of ReactN is to behave as if global state were built into React. You do not have to import previous state setting to use hooks like `useState` or `useReducer`, so you shouldn't have to to use `useGlobal` either.

It makes writing the library easier in that we know the shape of the state from `setGlobal`, but it does not make the implementation of setting global state easier on the user. This is nice for TypeScript users, but it does not add any benefit to vanilla/ES6 JavaScript users. It is strictly more difficult for them with no benefit. And even for TypeScript users, it's giving them a burden of importing the return value just because ReactN has trouble implementing the state itself. It makes more sense for TypeScript users to be able to just `useGlobal` and it just somehow know the shape of the state.

Although in that regard, if I'm already using:

```JavaScript
import { useGlobal } from './wherever/i/created/state';
useGlobal('key');
```

It's not much different to use this instead:
```JavaScript
import { IGlobalState } from './wherever/i/created/state';
useGlobal<IGlobalState['key']>('key')
```

Maybe `useGlobal` could accept an interface for the global state instead of its return type, and infer the return type from that.

```JavaScript
import { IGlobalState } from './wherever/i/created/state';
useGlobal<IGlobalState>('key')
```

If you wanted to export your own `useGlobal` function that is just `useGlobal<IGlobalState>`, you could.

In fact, you can likely do that with the current implementation:

```
import { useGlobal as _useGlobal } from 'reactn';

interace IGlobalState {
  describe: string;
  shape: boolean;
  here: number;
}

export function useGlobal(property: keyof IGlobalState, setterOnly: boolean = false) {
  return _useGlobal<IGlobalState[property]>(property, setterOnly);
}
```

I may be wrong, but something like that may be what you are looking for? I'm not sure if `IGlobalState[property]` will compile, but you are probably better at TypeScript than myself and can get it to work.

For TS users, creating and exporting this function is equivalent to the work required to create and export your suggested `useGlobal` as the return value of `setGlobal`.

However, for vanilla JS users, they do not need to create and export this function and continue to use `useGlobal` without importing or exporting anything.

**Comment by mmkal** [comment]
> For reference, the state object is never undefined. It instantiates to an empty object. If you never call setGlobal, the state isn't undefined, it is just {} with no properties.

Ok - that's a secret rule that the type definitions don't tell you.

> I want to avoid any at all costs

I agree - that's why I was suggesting this behaviour would be explicitly unsupported by this library, and recommended against. That's exactly the sort of escape-hatch `any` is good for. If a consumer _really_ thinks they know better, they can try and subvert what the types are guiding them to do. They _should_ need to put a `// tslint:disable` in to allow unsupported things!

> I'm just not sure I see having to import the return value of setGlobal in all your files as easier than not having to import anything

You already have to `import { useGlobal } from 'reactn'`. Why is that better than `import { useGlobal } from './my-global-state'`? You're just importing a single hook to do a single thing, either way.

> This is nice for TypeScript users, but it does not add any benefit to vanilla/ES6 JavaScript users

JS users would get type hints. VSCode also has a mode where it will show errors for wrong type usage even in JavaScript, so they would see when they use the state wrongly:

![image](https://user-images.githubusercontent.com/15040698/53976251-a828c780-40d4-11e9-9b76-a79abdf1fe0c.png)

> Although in that regard, if I'm already using:
>
> ```typescript
> import { useGlobal } from './wherever/i/created/state';
> useGlobal('key');
> ```
> It's not much different to use this instead:
>
> ```typescript
> import { IGlobalState } from './wherever/i/created/state';
> useGlobal<IGlobalState['key']>('key')
> ```

I disagree with this. The second one is more verbose (there's actually a missing `import { useState } from 'reactn'` in your example), requires manually passing in the generic type, so it's different from how you'd use the API in vanilla JS (and therefore gets no type hints in js projects), _and_ it's unsafe. I could pass whatever I wanted into that generic, there would be no errors, and the compiler would actually _prevent_ me from using the state correctly:

```typescript
const [wrongState] = useGlobal<{ thisValueDoesntExist: string }>('thisKeyDoesntExistEither')
```
_______

Here's a minimal working example that I think looks quite clean and is type-safe. It just uses plain old react hooks; it supports multiple stores without resorting to `any`, and doesn't require shimming the whole of react:

```typescript
// global-state.tsx
import { createContext, useContext, useState } from 'react'

export function setGlobal<T>(initialState: T) {
  const initialise = () => useState(initialState)
  const Context = createContext([initialState, () => {}] as ReturnType<typeof initialise>)
  const useGlobal = () => useContext(Context)
  const useGlobalProvider = () => {
    const initialStateTuple = initialise()
    return ({children}: {children: React.ReactNode}) => (
      <Context.Provider value={initialStateTuple}>
        {children}
      </Context.Provider>
    )
  }
  return { useGlobal, useGlobalProvider }
}
```
```typescript
// state.ts
import {setGlobal} from './global-state'

export const { useGlobal, useGlobalProvider } = setGlobal(0)
```
```typescript
// components.tsx
import {useGlobal} from './state'

export const Increaser = () => {
  const [count, setCount] = useGlobal()
  return (<>
    <div>Counter is {count}</div>
    <button onClick={() => setCount(count + 5)}>add five</button>
  </>)
}

export const Decreaser = () => {
  const [count, setCount] = useGlobal()
  return (<>
    <div>Counter is {count}</div>
    <button onClick={() => setCount(count - 10)}>subtract ten</button>
  </>)
}
```
```typescript
// app.tsx
import {Decreaser, Increaser} from './components'
import {useGlobalProvider} from './state'

export default () => {
  const Provider = useGlobalProvider()
  return (
    <Provider>
        <Increaser />
        <Decreaser />
    </Provider>
  )
}
```

I get appropriate errors if I try to use the state wrongly:
![image](https://user-images.githubusercontent.com/15040698/53976860-d955c780-40d5-11e9-8770-c7e2a1e73c3e.png)

**Comment by CharlesStover** [comment]
I'm revamping this issue, if it's okay, to change state behavior to support non-object types. I think the closest alignment to the original request that I am willing to support is `createProvider(0)`. You can use `createProvider({ count: 0 })` in ReactN already to generate a state and associated reducers that you can import and use in your Components. The only difference is it won't support `setGlobal(1)` and instead must be `setGlobal({ count: 1 })`, but other than that, you are still able to segment this part of the state from the rest and use `Provider.useGlobal()` to access it as a hook.

With non-object states, you could do:
```JavaScript
// state.ts
import { createProvider } from 'reactn';
export default createProvider(0);
```
```JavaScript
// components.tsx
import { useGlobal } from './state';

export const Increaser = () => {
  const [count, setCount] = useGlobal();
  return (<>
    <div>Counter is {count}</div>
    <button onClick={() => setCount(count + 5)}>add five</button>
  </>)
}

export const Decreaser = () => {
  const [count, setCount] = useGlobal();
  return (<>
    <div>Counter is {count}</div>
    <button onClick={() => setCount(count - 10)}>subtract ten</button>
  </>)
}
```

I believe this is exactly the same as your last comment, except you don't have to wrap provider around your app because it isn't using Context.

Non-object states aren't planned for the 2.0 milestone, but I toyed with and support them. They aren't on the roadmap because it was difficult to get them to play well with TypeScript. Once 2.0 launches, it may be easier to revisit the issue in a codebase that is 100% TypeScript.

**Comment by CharlesStover** [comment]
I'm going to close this issue now.

For the time being, supporting non-object global states is not on the roadmap.

As of 2.0, you can [globally set the default state and reducers](https://github.com/CharlesStover/reactn/blob/master/docs/src/global.d.ts), which tackles the OP's original issue of TypeScript inferrance. :)

Thank you for all the info. I hope 2.0 resolved this satisfactorily.
