### ISSUE TITLE
[TypeScript] Default global state types are lost.

### ISSUE THREAD

**Issue by efichot** [CharlesStover/reactn#50]
When I tried to type my global state inside my setGlobal(), when I retrieve my field with useGlobal() I lost the typing, ts say me my variable is of type 'any'.

**Comment by CharlesStover** [comment]
This is correct, unfortunately. There's no way for it to know. If you change the shape of the global state in another file, useGlobal can't know that or the new shape in order to tell you the type it is returning.

You can use `useGlobal<Type>('property')` to tell it the type.

I'm working on a complete rewrite of ReactN in TypeScript that should improve upon this system.. While types can't be inferred by useGlobal, they'll at least we inferred by Provider and supported by more helper functions than present.

**Comment by CharlesStover** [comment]
This is fixed in the latest commit for 2.0, so closing this. :)

Thank you for your feedback!
