### ISSUE TITLE
useGlobal error: Argument of type "value" is not assignable to parameter of type 'never'

### ISSUE THREAD

**Issue by Nephrited** [CharlesStover/reactn#77]
When attempting to do the following:

`const [, setValue] = useGlobal("value");`

I get a typescript error of:

`Argument of type '"value"' is not assignable to parameter of type 'never'.`

This is with reactn: ^2.0.1 and react: ^16.8.6.

TS is reporting useGlobal as `(alias) useGlobal<State, never>(property: never): [never, Setter<State, never>] (+1 overload)`

This worked fine in versions prior to 2.0.0.

**Comment by CharlesStover** [comment]
This is because TypeScript does not have a shape for your global state. Your code says to get the value property of an empty object, and TS is warning you (incorrectly) that that property does not exist. You can set the shape of your global state in three different ways. No one way is more correct than the other, so use whichever you are the most comfortable with.

First and easiest, you can define your global state in `src/global.d.ts`. [Here](https://github.com/CharlesStover/reactn/blob/master/docs/src/global.d.ts) is a template for that. If you don't have reducers, you don't need to include the Reducers interface. You can just delete the whole Reducers block. The State interface is the real magic here. Add a value property and whatever type value is, e.g. `value: string;`. Your code should then work.

Another way to do this without modifying a global TypeScript file is to define that global state interface and pass it as a generic to `useGlobal`. So something like `interface G { value: string; }` and `useGlobal<G>('value')`.

Lastly if you want to use a Provider (check Provider.md in this repo), then types can be inferred from the Provider's shape automatically, but you increase boilerplate by a few lines to achieve it, since your provider must be imported and your App must be wrapped in that Provider.

My recommendation is the global.d.ts file, as it was designed to be the least amount of effort and requires no boilerplate -- no imports, no wrapper components, it just works auto-magically.

Let me know if this is a satisfactory solution to your issue.

**Comment by Nephrited** [comment]
Went with the `global.d.ts` solution, worked like a charm.

I already had a set of typings set up for global state, so I just imported the interfaces as relevant and that seemed to take just fine.

Feature request: Inherit the typings from the initial state for TS purposes?

At any rate, perfect. Thank you!

**Comment by CharlesStover** [comment]
It's not possible for TypeScript to inerehit the global state shape from `setGlobal` unfortunately, which is why the global.d.ts solution was added. It can inherit the state shape from `createProvider`, which is why that works.

Glad you got it solved. I have a feeling this will come up for a lot of users, so I'll try to get this exact error into the documentation.
