### ISSUE TITLE
Module `redux` does not exist in the Haste module map

### ISSUE THREAD

**Issue by chrise86** [CharlesStover/reactn#79]
Using this with React Native, as soon as the app boots I get the following error:
```
error: bundling failed: Error: Unable to resolve module `redux` from `/Users/chrisedwards/Apps/ReactNative/MyApp/node_modules/reactn/build/utils/redux-dev-tools.js`: Module `redux` does not exist in the Haste module map
```
I can see `redux` listed as a devDependency, but it's not getting installed and I can't see any mention of needing it in the docs.

---

```
react 16.8.3
reactn 2.0.1
```

**Comment by CharlesStover** [comment]
It should be an optional dependency and compile without it. If the React Native bundler doesn't treat it as optional the way the browser bundler does, for an easy fix, you can install redux. It is just used for the dev tools debugger, and you aren't expected to write any reduce boilerplate whether or not it's installed.

There is an issue open now to move the dev tools debugger to an external package so that the optional dependency warning doesn't appear. Once that issue is resolved, this one also will be.

**Comment by CharlesStover** [comment]
Just as a heads up, this is completed and will be deployed today in version `2.0.2`.
