### ISSUE TITLE
if i use multiple global states, react-redux or reactn which is better?

### ISSUE THREAD

**Issue by JiangWeixian** [CharlesStover/reactn#97]
reactn is awsome repo, it solves a lot of problems for me

but I have some questions?

if I have a huge state tree in my project. It is recommended to use reactn?

for example, I create 20-30 pages, it's a good idea by createprovider for each page?

thx.

**Comment by CharlesStover** [comment]
Providers aren't needed at all. They are only there for your convenience. If at any point you want to say, "I don't want this state mixed with the rest of my state," e.g. due to a risk of overlapping property names, separation of concerns, or separating state by component, then feel free to create a Provider for that chunk of state.

At no point should creating a Provider feel like an inconvenience for you. :)

The point of ReactN, unlike Redux, is that you have full control over your decision-making process as far as how, when, and why you interact with the global state. For example, you are not forced into Flux architecture, but Flux architecture is supported if you want to use it.

A ReactN Provider is very similar to a Redux Provider. If you wouldn't have a new Redux store provided there (`<Provider store={newReduxStore}>`), you likely wouldn't have a ReactN Provider there either.
